const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');

const version = fs.readFileSync('VERSION', 'utf8').trim();
assert(/^\d+$/.test(version), 'VERSION debe ser numérica');
const html = fs.readFileSync('conexion-sql.html', 'utf8');
const nucleo = fs.readFileSync('nucleo.html', 'utf8');
const bat = fs.readFileSync('CAPITAN_RODOLFO.bat', 'utf8');
const inline = html.match(/<script>\s*([\s\S]*?)<\/script>/i);
assert(inline, 'Núcleo/Datos debe incluir script');
new vm.Script(inline[1], {filename:'conexion-sql.html'});
const source = inline[1];

assert(html.includes('id="discoverLocal"'), 'Botón buscar locales');
assert(html.includes('id="discoverNetwork"'), 'Botón de red manual');
assert(html.includes('NÚCLEO · DATOS · v' + version), 'Datos debe mostrar VERSION');
assert(html.includes("logDiag('Página v" + version), 'Diagnóstico de Datos debe mostrar VERSION');
assert(nucleo.includes('id="nucleoVersion">' + version), 'Núcleo debe mostrar VERSION');
assert(nucleo.includes('CAPITAN_RODOLFO.bat?v=' + version), 'Núcleo descarga la versión actual');
assert(source.includes('await discoverServers(false);'), 'El equipo se busca si no está conectado');
assert(source.includes("await post('/api/discover-servers',{})"), 'La red se busca sólo con botón');
assert(!html.includes('value="DUILIO\\\\SQLEXPRESS"'), 'No incluir nombre de servidor fijo');
const bridge = fs.readFileSync('bridge/capitan_rodolfo_local.ps1','utf8');
assert(bridge.includes('function Get-DiscoveredSqlServers'), 'Descubrimiento en el servicio SQL');
assert(bridge.includes('Wait-Job -Job $job -Timeout 6'), 'Red acotada a seis segundos');
assert(bridge.includes('if($Network){'), 'No escanear la red sin opción explícita');
assert(bat.includes('set "EXPECTED_VERSION="'), 'El BAT inicializa versión sin duplicarla');
assert(bat.includes('do if not defined EXPECTED_VERSION set "EXPECTED_VERSION=%%V"'), 'El BAT lee VERSION descargada');
console.log('OK: Núcleo, Datos y el instalador comparten VERSION=' + version + ', con detección SQL opcional.');
