const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const html = fs.readFileSync('conexion-sql.html','utf8');
const inline = html.match(/<script>\s*([\s\S]*?)<\/script>/i);
assert(inline,'Núcleo/Datos debe incluir script');
new vm.Script(inline[1],{filename:'conexion-sql.html'});
const source = inline[1];
assert(html.includes('id="discoverLocal"'),'Botón buscar locales');
assert(html.includes('id="discoverNetwork"'),'Botón de red manual');
assert(source.includes("const expected='86'"),'UI y bridge de la misma versión');
assert(source.includes('await discoverServers(false);'),'El equipo se busca si no está conectado');
assert(source.includes("await post('/api/discover-servers',{})"),'La red se busca sólo con botón');
assert(!html.includes('value="DUILIO\\\\SQLEXPRESS"'),'No incluir nombre de servidor fijo');
const bridge = fs.readFileSync('bridge/capitan_rodolfo_local.ps1','utf8');
assert(bridge.includes('function Get-DiscoveredSqlServers'),'Descubrimiento en el servicio SQL');
assert(bridge.includes('Wait-Job -Job $job -Timeout 6'),'Red acotada a seis segundos');
assert(bridge.includes("if($Network){"),'No escanear la red sin opción explícita');
assert.equal(fs.readFileSync('VERSION','utf8').trim(),'86');
assert(fs.readFileSync('CAPITAN_RODOLFO.bat','utf8').includes('EXPECTED_VERSION=86'));
console.log('OK: interfaz de Datos sintácticamente válida, endpoints, versión y escaneo opcional.');
